### ISSUE TITLE
[SoD] Argent Dawn missing reagents for upgrade items

### ISSUE THREAD

**Issue by Xdembe** [Aleks1015/AtlasLootClassic_Era#21]
**AtlasLoot version**
3.5.20
**Lua error**
no errors
**Describe the bug**
no reagents for upgrade items with Argent Dawn
**To Reproduce**
watch screenshots
**Expected behavior**
showing reagents like Thorium Brotherhood or Timbermaw Hold
**Screenshots**
![image](https://github.com/user-attachments/assets/db6b96bc-9a2e-4546-bc2f-5056178c44af)
![image](https://github.com/user-attachments/assets/afaac1d8-ff40-4614-b56e-7c94d6ff536f)

**Additional context**

**Comment by Aleks1015** [comment]
Hey @Xdembe

I believe this is related to an issue with bad data being saved into the addon's saved variables.  I'm looking into why this is happening but I suspect it is when changes are made.  I'm trying to find a way to clear some of this as it seems to be very isolated.

Try deleting the saved variables for AtlasLoot located in the WTF folder (WTF -> Account -> Account_Name -> SavedVariables)  You will need to do this while logged out in the character selection screen or with the game close because when you logout or refresh your UI - the client will save all saved variables.

Let me know if this solves your issue.

If you have any favourites, they would be stored here so you may lose them.

![image](https://github.com/user-attachments/assets/863425cb-8363-4b6d-8fe6-800ab56be735)

**Comment by Xdembe** [comment]
That works, but now missing main item
![image](https://github.com/user-attachments/assets/7fa45d10-3c6c-45d6-b996-2574ce0e1e1e)

**Comment by Aleks1015** [comment]
You're welcome! @Xdembe 

Yes that I missed - will hold this issue open to add later tonight or tomorrow.

Thanks!

**Comment by Aleks1015** [comment]
This has been included in 3.5.21 pending to be released
